apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: novapay-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: user.novapay.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: novapay-web-user
                port:
                  number: 3000

    - host: merchant.novapay.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: novapay-web-merchant
                port:
                  number: 3003

    - host: api.novapay.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: novapay-api
                port:
                  number: 3001
